name: Deploy MultiDocker

on:
  push:
    branches:
      - main  # Change this if your default branch is 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Test React App
        run: |
          docker build -t dackevall/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true dackevall/react-test npm test

      - name: Build Production Images
        run: |
          docker build -t dackevall/multi-client ./client
          docker build -t dackevall/multi-nginx ./nginx
          docker build -t dackevall/multi-server ./server
          docker build -t dackevall/multi-worker ./worker

      - name: Push Images to Docker Hub
        run: |
          docker push dackevall/multi-client
          docker push dackevall/multi-nginx
          docker push dackevall/multi-server
          docker push dackevall/multi-worker

